#!/usr/bin/env bash
# This script is displaying "Alx School" 10 times
file_h="alxschool"

if [ -e "$file_h" ]
then

    echo "alxschool file exists"
    if [ -s "$file_h" ]
    then
        echo "alxschool file is not empty"
    else
        echo "alxschool file is empty"
    fi

    if [ -f "$file_h" ]
    then
        echo "alxschool is a regular file"
    fi
else
    echo "alxschool file does not exist"
fi
